name: Wake Up Streamlit Apps

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0,6,12,18 * * 0-6"  # Runs at 09:00 and 17:00 Rome time on weekdays (CET: UTC+1)
    #- cron: "0 11 * * 0,6"    # Runs at 12:00 Rome time on weekend (CET: UTC+1)

jobs:
  wake-up:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install selenium

      - name: Run Python script to wake up Streamlit apps
        run: python wake_up_streamlit.py

      - name: Upload log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: wakeup-log
          path: wakeup_log.txt
